### ISSUE TITLE
[config] nested `runs`

### ISSUE THREAD

**Issue by tristan-f-r** [Reed-CompBio/spras#296]
Currently, runs are specified per-algorithm as so:

```yaml
run1:
  a: 5
  b: 6
run2:
  a: 4
  b: 5
```

Instead, we should organize this to be nested inside `runs` for better compatibility with keys we may add to algorithm (e.g. `include`) in the future.

```yaml
runs:
  run1:
    a: 5
    b: 6
  run2:
    a: 4
    b: 5
```

This has parsing (no extraneous key support) and readability benefits.
