### ISSUE TITLE
`containers`

### ISSUE THREAD

**Issue by tristan-f-r** [Reed-CompBio/spras#297]
Config file options should be under a general `containers` rule, so we can not only specify it per config, but also per algorithm and per analysis.

Essentially, moving:

```yaml
container_framework: docker
unpack_singularity: false
container_registry:
  base_url: docker.io
  owner: reedcompbio
```

to:

```yaml
containers:
  framework: docker
  unpack_singularity: false
  registry:
    base_url: docker.io
    owner: reedcompbio
```
